export let config = {
    "token": process.env.TOKEN,
    "prefix": "p!",
    "commands": [
        "about",
        "creator",
        "play",
        "join",
        "leave",
        "johnny",
        "cry",
        "airhorn",
        "diddy",
        "porygon",
        "anana",
        "ruby",
        "papyrus",
        "fuck",
        "nash",
        "bug",
        "terry",
        "at4wquest",
        "d4",
        "d6",
        "d10",
        "d12",
        "d20",
        "d100",
        "flip",
        "stop",
        "list",
        "help"
        
    ]
}