export let config = {
    "token": process.env.TOKEN,
    "prefix": "p!",
    "commands": [
        "about",
        "creator",
        "play",
        "join",
        "leave",
        "johnny",
        "pet",
        "swing",
        "cry",
        "rights",
        "airhorn",
        "diddy",
        "porygon",
        "anana",
        "ruby",
        "papyrus",
        "linkara",
        "fuck",
        "nash",
        "bug",
        "knife",
        "birthday",
        "terry",
        "at4wquest",
        "harvester",
        "jeffrey",
        "roll",
        "flip",
        "8ball",
        "secret",
        "funny",
        "noot",
        "cheer",
        "stop",
        "list",
        "help",
        "moonball",
        "garrus"
        
    ]
}